# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check-strict:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # CRAN does not provide macOS binaries for R-devel, so some packages
          # need to be built from source. To avoid that, use R-release.
          - { os: macos-latest, r: "release" }
          - { os: windows-latest, r: "devel" }
          - { os: ubuntu-latest, r: "devel" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: "release"
          use-public-rspm: true

      - name: Install packages from source
        run: |
          install.packages(c("Matrix", "TMB"), type = "source")
        shell: Rscript {0}

      ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ##                              IMPORTANT                                       ##
      ##                                                                              ##
      ##             Strict checks are run only on R-release and R-devel.             ##
      ##  No deps are ignored since all deps ought to be available on these versions  ##
      ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          #cache-version: 2
          pak-version: devel
          extra-packages: |
            any::rcmdcheck
            any::BH
            TMB=?ignore-before-r=100.0.0
            Matrix=?ignore-before-r=100.0.0
            glmmTMB=?ignore-before-r=100.0.0
          needs: check

      # install *after* other deps to avoid FreeADFunObject error
      - name: Install glmmTMB from source
        run: |
          install.packages("glmmTMB", type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: '"note"'